spring:
  application:
    name: room-service
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/room_service?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
#  servlet:
#    context-path: /room-service
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.hilltop: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:/home/leel/Desktop/logs}
