spring:
  application:
    name: room-service
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL:jdbc:mysql://34.224.6.43:3306/room_service?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
#  servlet:
#    context-path: /room-service
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://54.210.130.67:8761/eureka